#!/usr/bin/env node
/**
 * `tsc --noEmit`, minus the diagnostics that come from the gluestack-ui v5
 * components in src/components/ui.
 *
 * Those files are generated by `gluestack-ui add` and must not be hand-edited
 * (CLAUDE.md rule 6). While v5 is pre-stable a handful of them do not typecheck
 * against RN 0.86 / reanimated 4 — none of it is our code, and none of it is
 * fixable without editing generated output. Everything else is checked
 * strictly, and a failure here still fails the build.
 *
 * Delete this script and go back to plain `tsc --noEmit` once gluestack-ui v5
 * typechecks cleanly.
 */
import { spawnSync } from 'node:child_process';

const IGNORED_PREFIX = 'src/components/ui/';

const result = spawnSync('npx', ['tsc', '--noEmit', '--pretty', 'false'], {
  encoding: 'utf8',
});

const lines = `${result.stdout ?? ''}${result.stderr ?? ''}`
  .split('\n')
  .filter((line) => line.trim().length > 0);

let ignored = 0;
const reported = [];
let keepingCurrent = false;

for (const line of lines) {
  const isDiagnosticStart = /^\S.*\(\d+,\d+\): (error|warning) TS\d+:/.test(line);
  if (isDiagnosticStart) {
    keepingCurrent = !line.startsWith(IGNORED_PREFIX);
    if (!keepingCurrent) ignored += 1;
  }
  if (keepingCurrent) reported.push(line);
}

for (const line of reported) console.error(line);

if (ignored > 0) {
  console.error(
    `\n${ignored} diagnostic(s) in ${IGNORED_PREFIX} ignored (generated gluestack-ui v5 components).`,
  );
}

const failed = reported.some((line) => line.includes(': error TS'));
process.exit(failed ? 1 : 0);
